### PR TITLE
Add escaping

### PR DESCRIPTION
**Pull request by pdewouters**

### CODE REVIEW

**Comment by Benunc** [comment]
Hi Paul! Thanks so much for the PR. I am in the midst of a major rewrite of the plugin to OOP, which is taking place on the release/6.0 branch. I am going to test this with the master branch and potentially merge it, but can you also have a look at the 6.0 release branch and see if escaping is needed there too.

Also, has this been tested with non-roman characters in the shortened text? I remember at one point having trouble with (for example) Greek text that was resolved somehow by not escaping. I just want to make sure to not break things for that subset of my users.

Thanks again for the PR!

**Comment by pdewouters** [comment]
You're welcome. Good to know there's a refactor going on. 

> Also, has this been tested with non-roman characters in the shortened text?
It has not. Do you mean like arabic or chinese?

**Comment by pdewouters** [comment]
Are you planning to make it a paid plugin? I see you added the EDD updater class

**Comment by Benunc** [comment]
I have made one paid addon, (premium styles) and plan to make an images one. I am going to handle the licensing through the core plugin, hence EDD updater. Currently the updater is in the addon, but that gets clunky in the second addon.

**Pull request merged**
