### PR TITLE
Add gutenberg block support

### PR DESCRIPTION
**Pull request by ajitbohra**
- Adds block for Gutenberg
- Supports all the parameter configured via Inspector Panel in edit mode
- Uses username from plugin option
- Frontend is rendered via PHP using existing shortcode
- Block uses the same CSS we apply to frontend

**Note:**
Need to check how it works with custom styles

better-click-to-tweet

### CODE REVIEW

**Comment by Benunc** [comment]
@ajitbohra I made a new branch for this so that I can test it. so far, looks great. will make some new issues if I see them.

**Comment by ajitbohra** [comment]
@Benunc 
Further working on 
- Refactoring the code 
- Testing premium styles
- Testing & fixing issues if any

The code is just mashup of my code practice. "tld-awesome-click-to-tweet" block implementation was done by my friend "Hardeep". We have been referring & learning from the same course/tutorial (WesBos & ZacGordan) also plugin share similar functionality :) feel free to attribute him.

Have checked "tld-awesome-click-to-tweet" code will push some code refactoring & improvements.

**Comment by Benunc** [comment]
Great! just making sure we attribute any code to comply with the GPL.

Also, I have some Language cleanup that I just pushed to the block.js file, for reference.

**Comment by ajitbohra** [comment]
Cool 

Have refactored the code #23 will push them with changes merged.

**Pull request merged**
