### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by garrett-eclipse**
recieve > receive
suport > support

Found in this translation - https://translate.wordpress.org/projects/wp-plugins/better-click-to-tweet/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7172118&filters%5Btranslation_id%5D=60192112

### CODE REVIEW

**Comment by Benunc** [comment]
Thanks for spotting that!

**Comment by garrett-eclipse** [comment]
No worries, all the best

**Comment by Benunc** [comment]
Heads up, this is live in version 5.7.2 on the .org repo, and ready to be correctly translated.

**Comment by garrett-eclipse** [comment]
Awesome thanks @Benunc

**Pull request merged**
