### PR TITLE
Added Catalan Translation

### PR DESCRIPTION
**Pull request by jonpasquier**
Hi, 

I would like to contribute back the catalan translation of your plugin.

Thanks for publishing it in the first place!

### CODE REVIEW

**Comment by Benunc** [comment]
So sorry to just now be responding to this. Can you contribute this translation through the official WordPress translation tool? I will help by alerting the translation team that it is there. You can do that here: https://translate.wordpress.org/projects/wp-plugins/better-click-to-tweet

**Comment by jonpasquier** [comment]
Hi, 

I've just translated all the string of the development trunk on translate.wordpress.org
They are currently with the waiting status. Not really sure how to do to get them approved...

**Comment by Benunc** [comment]
Thanks so much! I just reached out to the polyglots team on Slack, to see what a good next step is for that.

**Comment by jonpasquier** [comment]
Hi @Benunc , 
I see that the catalan translation is still waiting to be approved at translate.wordpress.org and I suppose it is why it hasn't been included in BCTT last releases.
Is there anything I can do to get it approved?
Thanks!

**Pull request closed without merging**
